spring:
  application:
    name: demo

  # Spring Bootの自動的なDB初期化機能を無効化
  sql:
    init:
      mode: never
      # mode: always #アプリケーション起動時にschema.sqlとdata.sqlが実行

  # H2 Database
  datasource:
    url: jdbc:h2:file:${h2.db.path:./data/reportdb};DB_CLOSE_DELAY=-1
    # url: jdbc:h2:mem:reportdb # メモリーベース
    driverClassName: org.h2.Driver
    username: reportuser
    password: reportuser

  # H2 Console (データベースの中身を確認できる管理画面)      
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    # Spring Securityのデバッグログ出力
    org:
      springframework:
      security: DEBUG

    # My Batisのデバッグログ出力
    com:
      example:
        demo:
          domain:
            mapper: DEBUG



